---
title: "vonBertalanffy model for Groupo Tortuguero green turtle data"
output: html_notebook
---

I try to fit von Bertelanffy growth curve to observed growth data of greens. 

```{r}

rm(list=ls())
library(jagsUI)
library(tidyverse)
library(lubridate)
library(reshape)
library(bayesplot)
library(ggridges)

save.rds <- TRUE

source("Mancini_functions.R")

# MCMC.params <- list(   n.chains = 3,
#                        n.samples = 50000,
#                        n.burnin = 30000,
#                        n.thin = 5)

dat.1.Cm <- get.data.Cm("data/GTC_Cm Data_updated_2020-04-28_TE_v2.csv")

#dat.1 <- get.data("data/GTC_20190725_Tomo_v2.csv")

# Lo doesn't have enough (>2) recaptures. 
#spp <- c("Cm", "Ei") #unique(dat.1$species)

MCMC.params <- list(n.chains = 3,
                    n.samples = 100000,
                    n.burnin = 60000,
                    n.thin = 5)

n.per.chain <- (MCMC.params$n.samples - MCMC.params$n.burnin)/MCMC.params$n.thin
  
```

Find those that were captured more than once: (or better to use more than twice since the dataset is so big?)

```{r}
s <- 1
jags.data <- Cm.vonBert.jags.data(dat.1.Cm)
data.vector <- as.vector(jags.data$jags.data$L) %>% 
  rep(each = MCMC.params$n.chains * n.per.chain)

MCMC.params$model.file <-  "models/Model_RlinfRk_L.txt"
if (!file.exists(paste0("RData/Rlinf_Rk_Cm_Aug2020.rds"))){
  parameters <- c('CV', 'k', 'A', 
                  'Linf', 'LinfMu', 'LinfSD', 
                  'Shape', 'rate', "loglik", #'kAlpha', 'kBeta', 
                  'deviance')
  jm.1 <- jags(data = jags.data$jags.data,
               #inits = inits,
               parameters.to.save= parameters,
               model.file = MCMC.params$model.file,
               n.chains = MCMC.params$n.chains,
               n.burnin = MCMC.params$n.burnin,
               n.thin = MCMC.params$n.thin,
               n.iter = MCMC.params$n.samples,
               DIC = T, 
               parallel=T)
  
  loo.out.jm.1 <- compute.LOOIC(loglik = jm.1$sims.list$loglik, 
                                data.vector = data.vector, 
                                MCMC.params = MCMC.params)
  
  # loglik.vec <- as.vector(jm.1$sims.list$loglik)
  # LogLik.jm.1 <- matrix(loglik.vec[!is.na(data.vector)], 
  #                       nrow = MCMC.params$n.chains * n.per.chain)
  # 
  # Reff.jm.1 <- relative_eff(exp(LogLik.jm.1),
  #                           chain_id = rep(1:MCMC.params$n.chains,
  #                                          each = n.per.chain),
  #                           cores = 4)
  # 
  # loo.out.jm.1 <- rstanarm::loo(LogLik.jm.1, 
  #                               r_eff = Reff.jm.1, 
  #                               cores = 4, k_threshold = 0.7)
  
  if(save.rds) saveRDS(jm.1, file = paste0("RData/Rlinf_Rk_Cm_Aug2020.rds"))
  if(save.rds) saveRDS(loo.out.jm.1, file = paste0("RData/LOO_Rlinf_Rk_Cm_Aug2020.rds"))
}
  
if (!file.exists(paste0("RData/Rlinf_Fk_Cm_Aug2020.rds"))){
  MCMC.params$model.file <- "models/Model_Rlinf_Fk.txt"
  parameters <- c('CV', 'k', 'A', 
                  'Linf', 'LinfMu', 'LinfSD', 
                  'Shape', 'rate', "loglik", #'kAlpha', 'kBeta', 
                  'deviance')
  
  jm.1 <- jags(data = jags.data$jags.data,
               #inits = inits,
               parameters.to.save= parameters,
               model.file = MCMC.params$model.file,
               n.chains = MCMC.params$n.chains,
               n.burnin = MCMC.params$n.burnin,
               n.thin = MCMC.params$n.thin,
               n.iter = MCMC.params$n.samples,
               DIC = T, 
               parallel=T)
  
  loo.out.jm.2 <- compute.LOOIC(loglik = jm.1$sims.list$loglik, 
                                data.vector = data.vector, 
                                MCMC.params = MCMC.params)
  
  if(save.rds) saveRDS(loo.out.jm.2, file = paste0("RData/LOO_Rlinf_Fk_Cm_Aug2020.rds"))
  
  if(save.rds) saveRDS(jm.1, file = paste0("RData/Rlinf_Fk_Cm_Aug2020.rds"))
  
} 

if (!file.exists(paste0("RData/Flinf_Fk_Cm_Aug2020.rds"))){
  MCMC.params$model.file <- "models/Model_Flinf_Fk.txt"
  parameters <- c('CV', 'k', 'A', 
                  'Linf',  "loglik",
                  'Shape', 'rate', #'kAlpha', 'kBeta', 
                  'deviance')
  
  jm.1 <- jags(data = jags.data$jags.data,
               #inits = inits,
               parameters.to.save= parameters,
               model.file = MCMC.params$model.file,
               n.chains = MCMC.params$n.chains,
               n.burnin = MCMC.params$n.burnin,
               n.thin = MCMC.params$n.thin,
               n.iter = MCMC.params$n.samples,
               DIC = T, 
               parallel=T)
  
  loo.out.jm.3 <- compute.LOOIC(loglik = jm.1$sims.list$loglik, 
                                data.vector = data.vector, 
                                MCMC.params = MCMC.params)
  
  if(save.rds) saveRDS(loo.out.jm.3, file = paste0("RData/LOO_Flinf_Fk_Cm_Aug2020.rds"))
  
  if(save.rds) saveRDS(jm.1, file = paste0("RData/Flinf_Fk_Cm_Aug2020.rds"))
  
} 

if (!file.exists(paste0("RData/Flinf_Rk_Cm_Aug2020.rds"))){
  MCMC.params$model.file <- "models/Model_Flinf_Rk.txt"
  parameters <- c('CV', 'k', 'A', 
                  'Linf',  "loglik",
                  'Shape', 'rate', #'kAlpha', 'kBeta', 
                  'deviance')
  
  jm.1 <- jags(data = jags.data$jags.data,
               #inits = inits,
               parameters.to.save= parameters,
               model.file = MCMC.params$model.file,
               n.chains = MCMC.params$n.chains,
               n.burnin = MCMC.params$n.burnin,
               n.thin = MCMC.params$n.thin,
               n.iter = MCMC.params$n.samples,
               DIC = T, 
               parallel=T)
  
  loo.out.jm.4 <- compute.LOOIC(loglik = jm.1$sims.list$loglik, 
                                data.vector = data.vector, 
                                MCMC.params = MCMC.params)
  
  if(save.rds) saveRDS(loo.out.jm.4, file = paste0("RData/LOO_Flinf_Rk_Cm_Aug2020.rds"))
  
  if(save.rds) saveRDS(jm.1, file = paste0("RData/Flinf_Rk_Cm_Aug2020.rds"))
  
} 


```

